### ISSUE TITLE
Use RxJS instead of promises

### ISSUE THREAD

**Issue by jmcdo29** [nestjsplus/cookies#3]
Any chance you'd mind if I make a PR to switch the interceptor to using RxJS methods instead of switching the Observable to a promise?

**Comment by johnbiundo** [comment]
Feel free!

**Comment by dsebastien** [comment]
It would be great for this PR to be included in a release.
I'm facing the same issue

**Comment by johnbiundo** [comment]
@dsebastien fixed in 1.0.4
