### ISSUE TITLE
Still wrong type in ClearCookies parameter in npm

### ISSUE THREAD

**Issue by kirit0s** [nestjsplus/cookies#5]
PR https://github.com/nestjsplus/cookies/pull/1 fix this. But package in npm still has old clear-cookies.decorator.d.ts.

**Comment by johnbiundo** [comment]
Have you tried 1.0.2?

**Comment by kirit0s** [comment]
Yes, it's about 1.02.

Screenshot from npm RunKit
![изображение](https://user-images.githubusercontent.com/14249148/74410723-ca7da600-4e4a-11ea-94cb-75542217a3da.png)

**Comment by johnbiundo** [comment]
@kirit0s Sorry for the delay on this.  Not sure how that happened, but should be fixed in 1.0.4 now.
