### ISSUE TITLE
Will this project upgrade to version 7.0.0 or stay under 6.0.0?

### ISSUE THREAD

**Issue by yaharga** [nestjsplus/cookies#6]
Nest just released version 7.0.0, through which [decorators now have access to the context](https://docs.nestjs.com/migration-guide#custom-route-decorators). Will you be upgrading, or keep it the same, as I assume the interceptors will be merged into the decorators now?

**Comment by johnbiundo** [comment]
For now, I have simply created a separate version path for Nest v7 support (v 1.1.x) and v6 support (v1.0.x).

I just pushed `1.1.0`, so let me know if you have any issues with Nest v7.
